const cardData = [
  { image:"src/images/elden-ring-cover-art.webp",
    title: "Elden Ring",
    genre: "Soulslike Fantasy Action RPG",
  },
  { image:"src/images/p3r.webp",
    title: "Persona 3 Reload",
    genre: "Turn-Based Japanese RPG",
  },
  { image:"src/images/lies_of_p.png",
    title: "Lies of P",
    genre: "Soulslike Action RPG",
  },
  { image:"src/images/ff7-rebirth.png",
    title: "Final Fantasy VII Rebirth",
    genre: "Turn-Based Japanese RPG",
  },
  { image:"src/images/helldivers.png",
    title: "Helldivers II",
    genre: "Third Person Squad-Based Shooter",
  },
  { image:"src/images/bow.png",
    title: "TLoZ: Breath of the Wild",
    genre: "Open World Action-Adventure",
  },
  { image:"src/images/tekken8.png",
    title: "Tekken 8",
    genre: "Fighting Game",
  },
  { image:"src/images/sf6.png",
    title: "Street Fighter 6",
    genre: "Fighting Game",
  },
  { image:"src/images/granblue.png",
    title: "Granblue Fantasy: Relink",
    genre: "Fantasy Action RPG",
  },
  { image:"src/images/apex.png",
    title: "Apex Legends",
    genre: "Battle Royale",
  }
]
export default cardData